$primary_paletteKeyColor = BD93F9
$secondary_paletteKeyColor = 50FA7B
$tertiary_paletteKeyColor = FF79C6
$neutral_paletteKeyColor = 282A36
$neutral_variant_paletteKeyColor = 44475A
$background = 120019
$onBackground = F8F8F2
$surface = 120019
$surfaceDim = 0A0010
$surfaceBright = 2A0038
$surfaceContainerLowest = 08000C
$surfaceContainerLow = 170022
$surfaceContainer = 1B0027
$surfaceContainerHigh = 22002F
$surfaceContainerHighest = 2A0038
$onSurface = F8F8F2
$surfaceVariant = 3E4153
$onSurfaceVariant = F8F8F2
$inverseSurface = F8F8F2
$inverseOnSurface = 282A36
$outline = 6272A4
$outlineVariant = 4D4F66
$shadow = 000000
$scrim = 000000
$surfaceTint = FF10F0
$primary = FF10F0
$onPrimary = 2A0038
$primaryContainer = 5E00A3
$onPrimaryContainer = FFD6FA
$inversePrimary = 8A2BE2
$secondary = 8A2BE2
$onSecondary = FFFFFF
$secondaryContainer = 4B0082
$onSecondaryContainer = E6D6FF
$tertiary = FFB3D9
$onTertiary = 2A0038
$tertiaryContainer = C9A0FF
$onTertiaryContainer = 2A0038
$error = FF5555
$onError = 282A36
$errorContainer = 4C3743
$onErrorContainer = FF5555
$primaryFixed = FF6EF9
$primaryFixedDim = FF10F0
$onPrimaryFixed = 2A0038
$onPrimaryFixedVariant = 5E00A3
$secondaryFixed = A855F7
$secondaryFixedDim = 8A2BE2
$onSecondaryFixed = FFFFFF
$onSecondaryFixedVariant = 4B0082
$tertiaryFixed = FFD6FA
$tertiaryFixedDim = FFB3D9
$onTertiaryFixed = 2A0038
$onTertiaryFixedVariant = 4B0082
$term0 = 282A36
$term1 = FF5555
$term2 = 50FA7B
$term3 = F1FA8C
$term4 = BD93F9
$term5 = FF79C6
$term6 = 8BE9FD
$term7 = F8F8F2
$term8 = 6272A4
$term9 = FF6E6E
$term10 = 69FF94
$term11 = FFFFA5
$term12 = D6ACFF
$term13 = FF92DF
$term14 = A4FFFF
$term15 = FFFFFF
$rosewater = F8F8F2
$flamingo = FFB86C
$pink = FF79C6
$mauve = BD93F9
$red = FF5555
$maroon = FF6E6E
$peach = FFB86C
$yellow = F1FA8C
$green = 50FA7B
$teal = 8BE9FD
$sky = 8BE9FD
$sapphire = 8BE9FD
$blue = BD93F9
$lavender = BD93F9
$klink = BD93F9
$klinkSelection = BD93F9
$kvisited = FF79C6
$kvisitedSelection = FF79C6
$knegative = FF5555
$knegativeSelection = FF5555
$kneutral = F1FA8C
$kneutralSelection = F1FA8C
$kpositive = 50FA7B
$kpositiveSelection = 50FA7B
$text = F8F8F2
$subtext1 = F8F8F2
$subtext0 = E6E6E6
$overlay2 = A0A0A0
$overlay1 = 8A8A8A
$overlay0 = 6272A4
$surface2 = 3E4153
$surface1 = 343746
$surface0 = 282A36
$base = 282A36
$mantle = 21222C
$crust = 191A21
$success = 50FA7B
$onSuccess = 282A36
$successContainer = 4D4F66
$onSuccessContainer = F8F8F2
